spring.application.name=inventory-management-backend

# ===============================
# DATABASE CONFIGURATION
# ===============================

spring.datasource.url=jdbc:mysql://localhost:3306/inventory_management_db
spring.datasource.username=root
spring.datasource.password=root

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER
# ===============================

server.port=8080

jwt.secret=ZmQ4YzQwZmQ3MjY0M2NhOWFkYjY2ZjI0ZjNkZWI4OTI0NWI3Y2E5NjA4M2Y5YzY5MjQzNjQ4MzQxM2E2NmM4NQ==
jwt.expiration=86400000